version: '3.1'

services:

  wordpress:
    build: .
    restart: always
    ports:
      - 90:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: fkwp
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: fkwp
    volumes:
      - wordpress:/app/public

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: fkwp
      MYSQL_USER: fkwp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
